spring.application.name=ToDoList

# H2 como ARQUIVO (DADOS PERSISTEM)
spring.datasource.url=jdbc:h2:file:./data/tododb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuracoes do Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.info.title=API ToDoList
springdoc.info.description=API para gerenciamento de tarefas (ToDo List)
springdoc.info.version=1.0.0